index:
    path: /
    controller: App\Controller\ServiceController::index

details:
    path: /{entreprise}/{name}/details
    controller: App\Controller\ServiceController::details

services:
    path: /entreprise/{entreprise}
    controller: App\Controller\EntrepriseController::services